#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔎 Validating curriculum data..."
node utils/validate-curriculum.js --glob "patterns/**/*.json" --strict --quiet || exit 1

echo "✅ All curriculum files passed validation!"
